package app.tauri.notification

/**
 * Fixed JNI bridge to the host app's Rust silent-push handler, generated by the
 * plugin's `silent_push_handler!` macro — the Android counterpart of the iOS
 * NSE's `dlsym` contract.
 *
 * [TauriFirebaseMessagingService] loads the app's native library (named by the
 * `app.tauri.notification.SILENT_PUSH_LIB` manifest meta-data) and calls
 * [process] for every data-only push, in every app state — including a Firebase
 * cold start where the Tauri runtime never initialized.
 *
 * @see TauriFirebaseMessagingService
 */
object SilentPushNative {
  /**
   * @param context the Application context, handed to the Rust side's optional
   *   `android_init` hook so a cold-started push process can replay the
   *   process-wide initializations the app normally performs at startup.
   * @param dataDir absolute path of the app's data directory
   *   ([android.content.Context.getDataDir]) — the same location Tauri's path
   *   API resolves on Android, so the handler can open the on-disk store the
   *   main app uses.
   * @param payloadJson the FCM data payload as a JSON object (string → string).
   * @return the `NotificationData` JSON to post, the `{"clearAll":true}`
   *   directive to dismiss every active notification, or `null` when the
   *   handler declines (the message then falls through to the JS
   *   `push-message` event).
   */
  @JvmStatic
  external fun process(context: android.content.Context, dataDir: String, payloadJson: String): String?
}
