//! iOS silent-push decoding for the Notification Service Extension (NSE).
//!
//! On iOS a Matrix-style push (`mutable-content: 1` + a fallback `alert`) is
//! handed to the app's NSE target in **every** app state — including after a
//! force-quit — with ~30 s to rewrite the content. The NSE links the same
//! staticlib as the app (linking it does not start Tauri, mirroring how the
//! Android FCM service loads the same `.so`) and resolves the C entry point
//! generated by [`tauri_plugin_notifications::ios_silent_push_handler!`] below
//! via `dlsym`. There is no Tauri `AppHandle` in that process, so we return the
//! content as [`NotificationData`] and let the extension render it.
//!
//! In a real Matrix client, [`crate::matrix_demo::simulate_matrix_fetch`] is
//! where `matrix_sdk::NotificationClient` would load and decrypt the event from
//! the store under `data_dir` — the App Group container shared with the main
//! app (see the `TauriNotificationsAppGroup` key in the NSE's Info.plist).
//!
//! If this handler returns `None` (or fails in any way), the extension shows
//! the push's own fallback `alert` (`loc-key: SINGLE_UNREAD`) instead.

use std::collections::HashMap;

use tauri_plugin_notifications::NotificationData;

/// Decode a Matrix push (`room_id` / `event_id` custom keys) into the
/// notification to display. Runs inside the NSE process.
// The by-value map is the `SilentPushHandler` contract (the handler owns the data).
#[allow(clippy::needless_pass_by_value)]
fn handle_silent_push(data_dir: &str, data: HashMap<String, String>) -> Option<NotificationData> {
    // No room/event → not a Matrix message push; keep the fallback alert.
    let room_id = data.get("room_id")?.clone();
    let event_id = data.get("event_id")?.clone();

    // A real client opens its Matrix SDK store under `data_dir` here, e.g.
    // `{data_dir}/matrix/<user>/db`, then decrypts the event via
    // NotificationClient. We mirror that async fetch on a short-lived runtime.
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .ok()?;
    let (sender, body) = runtime.block_on(async {
        // e.g. notification_client.get_notification(&room_id, &event_id).await
        let _ = data_dir;
        crate::matrix_demo::simulate_matrix_fetch(&room_id, &event_id)
    });

    // No `.id(...)`: the extension cannot change the identifier APNs assigned,
    // so the field is ignored on iOS. `group` (→ `threadIdentifier`) stacks the
    // room's notifications together instead. The deep link and the Matrix ids
    // ride in `extra`, whose string values surface in the `notificationClicked`
    // event's `data` when the user taps the notification.
    Some(
        NotificationData::builder()
            .title(sender)
            .body(body)
            .group(room_id.as_str())
            .summary(room_id.as_str())
            .extra(
                "deepLink",
                crate::matrix_demo::matrix_uri(&room_id, &event_id),
            )
            .extra("room_id", room_id)
            .extra("event_id", event_id)
            .build(),
    )
}

tauri_plugin_notifications::ios_silent_push_handler!(handle_silent_push);
