// The one silent-push handler for both mobile platforms (iOS NSE dlsym entry +
// Android FCM JNI entry, both generated by `silent_push_handler!`). See the
// module docs.
#[cfg(any(target_os = "android", target_os = "ios"))]
mod push_handler;

// Pure Matrix demo helpers (fetch/format) shared by the silent-push handler
// and the warm simulate command.
#[cfg(any(target_os = "android", target_os = "ios"))]
mod matrix_demo;

/// Demo-only command: feed a fake silent push through the exact handler an FCM
/// data message would reach, then show the result with the warm-path builder —
/// so the flow is testable without a Firebase backend.
// Tauri command handlers take owned args by convention (see the plugin's own
// `commands.rs`), and these are only consumed on Android.
#[tauri::command]
#[allow(clippy::needless_pass_by_value)]
#[cfg_attr(not(target_os = "android"), allow(unused_variables))]
fn simulate_silent_push(app: tauri::AppHandle, room_id: String, event_id: String) {
    #[cfg(target_os = "android")]
    {
        use tauri::Manager;
        use tauri_plugin_notifications::NotificationsExt;

        let mut data = std::collections::HashMap::new();
        data.insert("room_id".to_string(), room_id);
        data.insert("event_id".to_string(), event_id);
        // The same directory the FCM service passes the handler on a real push.
        let data_dir = app
            .path()
            .data_dir()
            .map(|dir| dir.display().to_string())
            .unwrap_or_default();

        let tauri_plugin_notifications::SilentPushResponse::Notification(notification) =
            push_handler::handle_silent_push(&data_dir, data)
        else {
            log::warn!("silent push handler declined the simulated payload");
            return;
        };
        let builder = app.notifications().builder().data(notification);
        // `show()` is async on mobile; don't block the command thread.
        tauri::async_runtime::spawn(async move {
            if let Err(e) = builder.show().await {
                log::error!("failed to show notification from silent push: {e}");
            }
        });
    }
    // On iOS the silent-push path runs in the Notification Service Extension,
    // a separate process this command can't reach — push a real payload
    // instead: `xcrun simctl push booted com.alexis.notiftestapp payload.apns`.
    #[cfg(not(target_os = "android"))]
    log::warn!("simulate_silent_push is Android-only; on iOS use `xcrun simctl push`");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Show INFO and above from everything by default, plus DEBUG from the
    // notifications plugin so UnifiedPush / D-Bus events are visible while
    // exercising the demo. Override at runtime with RUST_LOG=...
    env_logger::Builder::from_env(
        env_logger::Env::default()
            .default_filter_or("info,tauri_plugin_notifications=debug"),
    )
    .format_timestamp_millis()
    .init();

    log::info!("notifications-demo starting");

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notifications::init())
        // Handles the `matrix:` deep link a notification tap fires (Option B):
        // the OS routes the ACTION_VIEW intent here and the plugin reports the
        // URL to JS via `onOpenUrl` / `getCurrent`.
        .plugin(tauri_plugin_deep_link::init())
        .invoke_handler(tauri::generate_handler![simulate_silent_push])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
