//! iOS Notification Service Extension (NSE) support.
//!
//! iOS delivers a Matrix-style push (`mutable-content: 1` plus a fallback
//! `alert`) to the host app's Notification Service Extension in every app
//! state — including after a force-quit, where Android instead cold-starts the
//! plugin's messaging service. The NSE is a separate process without a Tauri
//! runtime, so — exactly like the Android killed-state `SilentPushHandler`
//! path — the decode step runs in the host app's own native library, not
//! through the plugin runtime.
//!
//! The plugin's Swift `TauriNotificationService` class (product
//! `tauri-plugin-notifications-nse` in `ios/Package.swift`) looks up the C
//! symbol `tauri_notifications_process_silent_push` via `dlsym`. The host app
//! exports that symbol from the same staticlib Tauri already builds
//! (`libapp.a`, which the NSE target also links) by invoking
//! [`ios_silent_push_handler!`](crate::ios_silent_push_handler) once:
//!
//! ```ignore
//! // src-tauri/src/ios_push.rs — compiled only for iOS
//! use std::collections::HashMap;
//! use tauri_plugin_notifications::NotificationData;
//!
//! fn handle_silent_push(
//!     data_dir: &str,
//!     data: HashMap<String, String>,
//! ) -> Option<NotificationData> {
//!     let room_id = data.get("room_id")?;
//!     let event_id = data.get("event_id")?;
//!     // Fetch/decrypt the event from the store under `data_dir`
//!     // (the App Group container shared with the main app), then:
//!     Some(
//!         NotificationData::builder()
//!             .title("Alice")
//!             .body("decrypted message")
//!             .group(room_id)
//!             .extra("deepLink", format!("matrix:roomid/{room_id}/e/{event_id}"))
//!             .build(),
//!     )
//! }
//!
//! tauri_plugin_notifications::ios_silent_push_handler!(handle_silent_push);
//! ```
//!
//! Returning `None` (or panicking, or taking longer than the ~30 s the system
//! grants) makes the extension deliver the push's original content, so the
//! payload's fallback `alert` (e.g. a `loc-key` like `SINGLE_UNREAD`) is shown
//! instead of dropping the notification.

use std::collections::HashMap;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

use crate::models::NotificationData;

/// Signature of a host silent-push handler passed to
/// [`ios_silent_push_handler!`](crate::ios_silent_push_handler).
///
/// * `data_dir` — the directory the extension resolved for shared app data
///   (the App Group container; see the Swift side's `TauriNotificationsAppGroup`
///   Info.plist key).
/// * `data` — the push payload's top-level custom keys (everything except
///   `aps`), stringified. The same shape Android's `SilentPushHandler` gets.
///
/// Return the notification content to display, or `None` to keep the push's
/// original (fallback) content.
pub type SilentPushHandler = fn(&str, HashMap<String, String>) -> Option<NotificationData>;

/// Backing implementation for the `tauri_notifications_process_silent_push`
/// symbol generated by [`ios_silent_push_handler!`](crate::ios_silent_push_handler).
///
/// Returns the handler's [`NotificationData`] serialized as a C string
/// allocated with [`CString::into_raw`], or null when the inputs are invalid,
/// the handler returns `None`, or it panics. A non-null return must be
/// released exactly once with [`free`].
///
/// # Safety
///
/// `data_dir` and `data_json` must be null or valid NUL-terminated C strings
/// that outlive this call.
#[doc(hidden)]
pub unsafe fn process(
    handler: SilentPushHandler,
    data_dir: *const c_char,
    data_json: *const c_char,
) -> *mut c_char {
    if data_dir.is_null() || data_json.is_null() {
        return std::ptr::null_mut();
    }
    // SAFETY: non-null, and the caller guarantees valid NUL-terminated strings.
    let (data_dir, data_json) = unsafe { (CStr::from_ptr(data_dir), CStr::from_ptr(data_json)) };
    let (Ok(data_dir), Ok(data_json)) = (data_dir.to_str(), data_json.to_str()) else {
        log::error!("silent push input is not valid UTF-8");
        return std::ptr::null_mut();
    };
    let data: HashMap<String, String> = match serde_json::from_str(data_json) {
        Ok(data) => data,
        Err(e) => {
            log::error!("failed to parse silent push data JSON: {e}");
            return std::ptr::null_mut();
        }
    };

    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| handler(data_dir, data)));
    let notification = match result {
        Ok(Some(notification)) => notification,
        Ok(None) => return std::ptr::null_mut(),
        Err(_) => {
            log::error!("silent push handler panicked");
            return std::ptr::null_mut();
        }
    };

    let json = match serde_json::to_string(&notification) {
        Ok(json) => json,
        Err(e) => {
            log::error!("failed to serialize notification: {e}");
            return std::ptr::null_mut();
        }
    };
    // JSON never contains interior NULs, but don't panic if that ever changes.
    CString::new(json).map_or(std::ptr::null_mut(), CString::into_raw)
}

/// Backing implementation for the `tauri_notifications_silent_push_free`
/// symbol generated by [`ios_silent_push_handler!`](crate::ios_silent_push_handler).
///
/// # Safety
///
/// `ptr` must be null or a pointer previously returned by [`process`] that has
/// not been freed yet.
#[doc(hidden)]
pub unsafe fn free(ptr: *mut c_char) {
    if !ptr.is_null() {
        // SAFETY: per contract, `ptr` came from `CString::into_raw` in
        // `process` and is released here exactly once.
        drop(unsafe { CString::from_raw(ptr) });
    }
}

/// Exports the C entry points the plugin's iOS Notification Service Extension
/// resolves with `dlsym`, wrapping a host handler of type
/// [`SilentPushHandler`](crate::nse::SilentPushHandler).
///
/// Invoke once, at the crate root or inside a `#[cfg(target_os = "ios")]`
/// module of your `src-tauri` crate. See the [`nse`](crate::nse) module docs
/// for the full walkthrough and an example.
///
/// The generated symbols are:
///
/// * `tauri_notifications_process_silent_push(data_dir, data_json) -> char*` —
///   returns the [`NotificationData`](crate::NotificationData) JSON to display,
///   or null to keep the push's fallback content.
/// * `tauri_notifications_silent_push_free(char*)` — releases a returned string.
#[macro_export]
macro_rules! ios_silent_push_handler {
    ($handler:path) => {
        /// Called by the plugin's Notification Service Extension via `dlsym`.
        ///
        /// # Safety
        ///
        /// The arguments must be null or valid NUL-terminated C strings; the
        /// non-null return value must be released exactly once with
        /// `tauri_notifications_silent_push_free`.
        #[no_mangle]
        pub extern "C" fn tauri_notifications_process_silent_push(
            data_dir: *const ::std::os::raw::c_char,
            data_json: *const ::std::os::raw::c_char,
        ) -> *mut ::std::os::raw::c_char {
            let handler: $crate::nse::SilentPushHandler = $handler;
            // SAFETY: the extension passes valid NUL-terminated C strings that
            // outlive the call.
            unsafe { $crate::nse::process(handler, data_dir, data_json) }
        }

        /// Releases a string returned by `tauri_notifications_process_silent_push`.
        ///
        /// # Safety
        ///
        /// `ptr` must be null or an unreleased return value of
        /// `tauri_notifications_process_silent_push`.
        #[no_mangle]
        pub extern "C" fn tauri_notifications_silent_push_free(ptr: *mut ::std::os::raw::c_char) {
            // SAFETY: per contract, `ptr` is null or came from `process` and is
            // released exactly once.
            unsafe { $crate::nse::free(ptr) }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    // The by-value map is the `SilentPushHandler` contract (hosts own the data).
    #[allow(clippy::needless_pass_by_value)]
    fn demo_handler(data_dir: &str, data: HashMap<String, String>) -> Option<NotificationData> {
        let room_id = data.get("room_id")?;
        Some(
            NotificationData::builder()
                .id(1)
                .title("Alice")
                .body(format!("event in {room_id} (store: {data_dir})"))
                .group(room_id)
                .extra("deepLink", format!("matrix:roomid/{room_id}"))
                .build(),
        )
    }

    crate::ios_silent_push_handler!(demo_handler);

    fn call(data_dir: &str, data_json: &str) -> Option<serde_json::Value> {
        let data_dir = CString::new(data_dir).expect("data_dir contains NUL");
        let data_json = CString::new(data_json).expect("data_json contains NUL");
        let ptr = tauri_notifications_process_silent_push(data_dir.as_ptr(), data_json.as_ptr());
        if ptr.is_null() {
            return None;
        }
        // SAFETY: non-null pointers from `process` are valid C strings until freed.
        let json = unsafe { CStr::from_ptr(ptr) }
            .to_str()
            .expect("returned JSON is not UTF-8")
            .to_string();
        tauri_notifications_silent_push_free(ptr);
        Some(serde_json::from_str(&json).expect("returned string is not valid JSON"))
    }

    #[test]
    fn round_trips_notification_json() {
        let json = call(
            "/data",
            r#"{"room_id":"!abc:matrix.org","event_id":"$xyz"}"#,
        )
        .expect("handler returned null");
        assert_eq!(json["id"], 1);
        assert_eq!(json["title"], "Alice");
        assert_eq!(json["group"], "!abc:matrix.org");
        assert_eq!(json["extra"]["deepLink"], "matrix:roomid/!abc:matrix.org");
        assert_eq!(json["body"], "event in !abc:matrix.org (store: /data)");
    }

    #[test]
    fn returns_null_when_handler_declines() {
        // No room_id → the demo handler returns None → fallback content.
        assert!(call("/data", r#"{"other":"key"}"#).is_none());
    }

    #[test]
    fn returns_null_on_malformed_json() {
        assert!(call("/data", "not json").is_none());
        assert!(call("/data", r#"{"nested":{"x":1}}"#).is_none());
    }

    #[test]
    fn returns_null_on_null_inputs() {
        let ptr = tauri_notifications_process_silent_push(std::ptr::null(), std::ptr::null());
        assert!(ptr.is_null());
        // Freeing null is a no-op.
        tauri_notifications_silent_push_free(std::ptr::null_mut());
    }
}
